version: '3.4'

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Nginx
    ports:
      - '90:90'
    container_name: nginx_php_create_user
    links:
      - php_app
    networks:
    - app-network

  php_app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: create_user_php
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-php
    env_file:
      - ./.env
    ports:
      - '3305:3306'
    expose:
      - 3305
    command: [ --default-authentication-plugin=mysql_native_password ]
    volumes:
      - ./config/db/:/docker-entrypoint-initdb.d
    networks:
      app-network:

networks:
  app-network:
    driver: bridge